---
- hosts: Junos_Switch
  vars:
    vlan_id: 
    vlan_name: 

  tasks:
    - name: Provision VLAN
      junos_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "{{ vlan_name }}"
        state: present

    - name: Show VLAN
      junos_command:
        commands: show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
