---
- hosts: Junos_Switch
  vars:
    vlan_id: 
    vlan_name: 

  tasks:
    - name: Provision VLAN
      junos_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "{{ vlan_name }}"
        state: present
        
    - name: Add VLAN to trunks
      junos_config:
        lines: 
        - set interfaces ge-0/0/9 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-0/0/11 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-0/0/14 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-0/0/17 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-0/0/23 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-1/0/10 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-1/0/11 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-1/0/12 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-1/0/13 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-1/0/14 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        - set interfaces ge-1/0/15 unit 0 family ethernet-switching vlan members "{{ vlan_name }}"
        
    - name: Show VLAN
      junos_command:
        commands: show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
