---
- hosts: 192.168.123.2
  vars:
    vlan_id: 998
    vlan_name: Ansible_VLAN

  tasks:
    - name: Provision VLAN
      connection: local
      junos_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "{{ vlan_name }}"
        state: present

    - name: Show VLAN
      junos_command:
        commands: show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
